# Generated by Django 3.1.13 on 2025-03-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='problem',
            field=models.TextField(default='test'),
        ),
    ]
